compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - level: discard
    pattern: "zombordle@workspace:. doesn't provide eslint-plugin-jest (*), requested by @tophat/eslint-config"

packageExtensions:
  "@types/react@*":
    dependencies:
      prop-types: "*"
      scheduler: "*"
  "@vitest/expect@*":
    dependencies:
      "@types/chai": "*"
  babel-plugin-styled-components@*:
    dependencies:
      "@babel/core": "*"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
