logFilters:
  - level: discard
    pattern: "zombordle@workspace:. doesn't provide eslint-plugin-jest (*), requested by @tophat/eslint-config"

packageExtensions:
  "@types/react@*":
    dependencies:
      "prop-types": "*"
      "scheduler": "*"
  "@vitest/expect@*":
    dependencies:
      "@types/chai": "*"
  "@rushstack/eslint-patch@*":
    dependencies:
      "@eslint/eslintrc": "*"
  "eslint-config-next@*":
    dependencies:
      "@eslint/eslintrc": "*"
      "next": "^13.2.3"
    peerDependencies:
      "react": "^18.0.0"
      "react-dom": "^18.0.0"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
