logFilters:
  - level: discard
    pattern: "zombordle@workspace:. doesn't provide eslint-plugin-jest (*), requested by @tophat/eslint-config"

packageExtensions:
  "@rushstack/eslint-patch@*":
    dependencies:
      "@eslint/eslintrc": "*"
  "@types/react@*":
    dependencies:
      prop-types: "*"
      scheduler: "*"
  "@vitest/expect@*":
    dependencies:
      "@types/chai": "*"
  eslint-config-next@*:
    dependencies:
      "@eslint/eslintrc": "*"
      next: ^13.2.3
    peerDependencies:
      react: ^18.0.0
      react-dom: ^18.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
