name: prepare-env
description: Prepares Envionrment

runs:
  using: "composite"

  steps:
    - name: Setup Node
      uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.3
      with:
        node-version-file: ".nvmrc"

    - name: Enable corepack
      run: corepack enable
      shell: bash

    - name: Restore Yarn Cache
      uses: actions/cache@40c3b67b2955d93d83b27ed164edd0756bc24049 # v4.0.2
      with:
        path: |
          .yarn/cache
          .pnp.*
        key: default-yarndeps-${{ hashFiles('yarn.lock') }}

    - name: Yarn Install
      run: yarn install --immutable
      shell: bash

    - name: Configure git
      run: |
        git config --global user.name ci-zombordle
        git config --global user.email imccausl@gmail.com
        git config --global init.defaultBranch main
      shell: bash
