name: CI Tasks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  prepare-env:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: eslint
        run: yarn lint

  lint-css:
    name: Lint CSS
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: stylelint
        run: yarn turbo run lint-css

  tests:
    name: Run All Tests
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: vitest
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, lint-css, tests]
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: Build
        run: CI=1 yarn build
      - name: Export Static Assets
        if: github.ref_name == 'main'
        run: yarn export && touch ./app/out/.nojekyll
      - name: Stash Build Artifacts
        if: github.ref_name == 'main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./app/out

  deploy:
    name: Deploy
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: Configure Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: "next"
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@af48cf94a42f2c634308b1c9dc0151830b6f190a
          
