name: CI Tasks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare-env:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: eslint
        run: yarn lint

  lint-css:
    name: Lint CSS
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: stylelint
        run: yarn lint:css
  
  tests:
    name: Run All Tests
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: vitest
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, lint-css, tests]
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: Cache Build Artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-build-cache-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-${{ hashFiles('**/yarn.lock') }}-
      - name: Build
        run: yarn build

  deploy:
    name: deploy
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/out
          key: ${{ runner.os }}-build-cache-${{ hashFiles('**/yarn.lock') }}-
      - name: Export Static Assets
        run: yarn export
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
      - name: Deploy to Pages
        uses: actions/deploy-pages@v1


          
      

