name: CI Tasks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare-env:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: eslint
        run: yarn lint

  lint-css:
    name: Lint CSS
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: stylelint
        run: yarn lint:css
  
  tests:
    name: Run All Tests
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: vitest
        run: yarn test
  

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, lint-css, tests]
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: Build
        run: yarn build 
      

