name: CI Tasks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env

      - name: Restore Turbo Cache
        uses: actions/cache@8469c94c6a180dfb41a1bd7e1b46ac557ea124f1 # v4.0.2
        with: 
          path: |
            .cache
            .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha}}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Lint
        run: yarn lint

      - name: Lint CSS
        run: yarn lint-css

      - name: Typecheck
        run: yarn typecheck

      - name: Run Tests
        run: yarn test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@955f1f08ad225eafd3396525634e1211cf89485f # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./app/coverage/clover.xml
          verbose: true

      - name: Build
        run: CI=1 yarn build
      - name: Export Static Assets
        if: github.ref_name == 'main'
        run: touch ./app/out/.nojekyll
      - name: Stash Build Artifacts
        if: github.ref_name == 'main'
        uses: actions/upload-pages-artifact@1780dfc2cece65a782cc86fa133f96aef8ad0345 # v3.0.1
        with:
          path: ./app/out


  deploy:
    name: Deploy
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: test-and-build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: Configure Pages
        uses: actions/configure-pages@dc1038695c94b221fd486193d8a760e736fa3816 # v.5.0.0
        with:
          static_site_generator: "next"
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@b74272834adc04f971da4b0b055c49fa8d7f90c9 # v4.0.5
          
